#!/bin/bash

echo "🔍 Checking for curves on your old contract..."
echo ""
echo "Run this on your server to check if you have curves on the old package:"
echo ""
echo "psql -U memeindexer -d memecoins << 'EOSQL'"
echo "-- Check for curves from old package (0x39d07cf...)"
echo "SELECT "
echo "  ticker,"
echo "  SUBSTRING(coin_type, 1, 50) as package_prefix,"
echo "  created_at,"
echo "  graduated"
echo "FROM tokens"
echo "WHERE coin_type LIKE '0x39d07cf%'"
echo "ORDER BY created_at DESC"
echo "LIMIT 10;"
echo ""
echo "-- Summary by package"
echo "SELECT "
echo "  SUBSTRING(coin_type, 1, 20) as package_start,"
echo "  COUNT(*) as curve_count"
echo "FROM tokens"
echo "GROUP BY SUBSTRING(coin_type, 1, 20)"
echo "ORDER BY curve_count DESC;"
echo "EOSQL"
echo ""
echo "If you see curves from 0x39d07cf..., we need to update the indexer to watch 3 packages!"
