[package]
name = "suilfg_launch"
version = "0.0.1"
published-at = ""
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.58.2", override = true }

# NOTE: Cetus removed for testnet compatibility (uses Simple AMM instead)

[dev-dependencies]

[addresses]
suilfg_launch = "0x0"
